apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/k8s/mnt/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-readonly-storage
spec:

  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
